### ISSUE TITLE
Add String Methods

### ISSUE THREAD

**Issue by sammaji** [sammaji/data-structure-and-algorithms#28]
Make a list of the most commonly used string functions in [01-string-functions.md](https://github.com/samyabrata-maji/JAVA-DSA-CODE/blob/ds/01-string-functions.md)

**Comment by Vinayakkamble07** [comment]
Any one assigned for this issue?

**Comment by sammaji** [comment]
No one is assigned on this issue.

**Comment by Vinayakkamble07** [comment]
what kind of methods can i add?

**Comment by sammaji** [comment]
basically i wish to implement all the commonly used methods like string.trim, string.substring, and so on and their use cases.

**Comment by Vinayakkamble07** [comment]
ok ill contribute? do you want example programs as well along with methods???

**Comment by sammaji** [comment]
That would be great. I'll assign you then.

**Comment by sammaji** [comment]
Thank you @Vinayakkamble07 for your contribution. Also did you know that if you put `#"issue-no"` in the commit message, it gets displayed under the issues section. [eg, `commit -m "updated file #26"`] and if you put "fixes", it closes the issue [eg, `commit -m "this fixes the problem #28"` will close issue #28]. Once again, thank you for your contribution 👍.
